return {
	
	'Air',
	'Water',
	
	-- Everyday blocks
	'Dirt', 
	'Grass Block',
	'Stone',
	'Cobblestone',
	'Oak Wood Planks',
	'Oak Leaves',
	'Oak Log',
	'Bedrock',
	'Sand',
	'Glass',
	
	-- Ore blocks
	'Coal Ore',
	'Gold Ore',
	'Iron Ore',
	'Diamond Ore',
	
	-- Tools
	'Wooden Pickaxe',
	'Wooden Axe',
	'Wooden Shovel',
	'Wooden Sword',
	
	'Stone Pickaxe',
	'Stone Axe',
	'Stone Shovel',
	'Stone Sword',
	
	'Iron Pickaxe',
	'Iron Axe',
	'Iron Shovel',
	'Iron Sword',
	
	'Diamond Pickaxe',
	'Diamond Axe',
	'Diamond Shovel',
	'Diamond Sword',
	
	'Coal',
	'Gold Ingot', 
	'Raw Iron',
	'Iron Ingot',
	'Diamond',

	-- Flowers
	'Grass',
	'Dandelion', 
	'Poppy',
	'Oxeye Daisy',
	
	-- Misc
	'Oak Sapling',
	'Apple'
}